feat(flame-graph-git): add the tool for all processes

diff --git a/flame-graph-git/bin_flame-graph b/flame-graph-git/bin_flame-graph
--- a/flame-graph-git/bin_flame-graph
+++ b/flame-graph-git/bin_flame-graph
@@ -37,10 +37,10 @@ EOF
 fi
 
 print_warning() {
-    echo -e "\033[33m$1\033[0m" >&2
+    echo -e "\033[33mWarning: $1\033[0m" >&2
 }
 print_error() {
-    echo -e "\033[31m$1\033[0m" >&2
+    echo -e "\033[31mError: $1\033[0m" >&2
 }
 
 # Warning about the perf.data and perf.svg
